#!/bin/bash

CONTAINER=$1

sudo lxc-create -n ${CONTAINER} -t download -- --dist ubuntu --release bionic --arch amd64

lxc-start ${CONTAINER}
sleep 15
cat <<EOF | lxc-attach ${CONTAINER} 
apt-get update
apt-get install openssh-server -y
echo "ALL    ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers.d/passwordless-sudo
useradd -m vagrant
mkdir -p /home/vagrant/.ssh/
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" > /home/vagrant/.ssh/authorized_keys
chmod 0600 /home/vagrant/.ssh/authorized_keys
chown -R vagrant:vagrant /home/vagrant/.ssh
echo -n "vagrant:vagrant" | chpasswd
EOF

lxc-stop ${CONTAINER}

DEST=/tmp/$1
mkdir -p ${DEST}
cp ubuntu-config ${DEST}/lxc-config

cd /var/lib/lxc/${CONTAINER}/
tar --numeric-owner --anchored --exclude=./rootfs/dev/log -czf ${DEST}/rootfs.tar.gz ./rootfs/*

cat <<EOF > ${DEST}/metadata.json
{
  "provider": "lxc",
  "version":  "1.0.0",
  "built-on": "<TODAY>"
}
EOF
cd ${DEST}
tar -czf /tmp/${CONTAINER}.box .
vagrant box remove ${CONTAINER}
vagrant box add /tmp/${CONTAINER}.box --name ${CONTAINER}
