#!/usr/bin/env python3
from argparse import ArgumentParser
from subprocess import Popen, PIPE

parser = ArgumentParser()

parser = ArgumentParser(description="devops-pipeline")
parser.add_argument("--file", default="platform-up.yml")
parser.add_argument("command", help="one of=setup,go")
args = parser.parse_args()

if args.command == "setup":
    print("Globally installing...")
    install_globally = Popen(["sudo", "bash", "-c", "echo export PATH=\${PATH}:$(pwd) > /etc/profile.d/platform-up-os.sh"])
    install_globally.communicate()

    print("Installing vagrant plugin")
    install_vagrant_lxc = Popen(["vagrant", "plugin", "install", "vagrant-lxc"])
    install_vagrant_lxc.communicate()
